language: java

jdk:
  - oraclejdk8
    - oraclejdk7
      - openjdk6

addons:
  sauce_connect:
    username: "arnarleifs"
    access_key: "6cbcb439-dfa0-4cb5-9f7f-7f5ff1c4ac3c"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

 before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

deploy:
  provider: heroku
  api-key:
    secure: "a8f14d51-efc4-417f-8b62-57e5ec74ad33"
  app: warm-sierra-2216

